/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardVoiceIndexRouteImport } from './routes/dashboard/voice/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardSheetsIndexRouteImport } from './routes/dashboard/sheets/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardMailIndexRouteImport } from './routes/dashboard/mail/index'
import { Route as DashboardFilesIndexRouteImport } from './routes/dashboard/files/index'
import { Route as DashboardDocumentsIndexRouteImport } from './routes/dashboard/documents/index'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts/index'
import { Route as DashboardSheetsDocumentIdRouteImport } from './routes/dashboard/sheets/$documentId'
import { Route as DashboardDocumentsDocumentIdRouteImport } from './routes/dashboard/documents/$documentId'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs-tick'
import { Route as ApiPublicBrevoWebhookRouteImport } from './routes/api/public/brevo-webhook'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardVoiceIndexRoute = DashboardVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSheetsIndexRoute = DashboardSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailIndexRoute = DashboardMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesIndexRoute = DashboardFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsIndexRoute = DashboardDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSheetsDocumentIdRoute =
  DashboardSheetsDocumentIdRouteImport.update({
    id: '/sheets/$documentId',
    path: '/sheets/$documentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocumentsDocumentIdRoute =
  DashboardDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs-tick',
  path: '/api/public/jobs-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrevoWebhookRoute = ApiPublicBrevoWebhookRouteImport.update({
  id: '/api/public/brevo-webhook',
  path: '/api/public/brevo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/files/': typeof DashboardFilesIndexRoute
  '/dashboard/mail/': typeof DashboardMailIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets/': typeof DashboardSheetsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice/': typeof DashboardVoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/files': typeof DashboardFilesIndexRoute
  '/dashboard/mail': typeof DashboardMailIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets': typeof DashboardSheetsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice': typeof DashboardVoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/files/': typeof DashboardFilesIndexRoute
  '/dashboard/mail/': typeof DashboardMailIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets/': typeof DashboardSheetsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice/': typeof DashboardVoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/contacts/'
    | '/dashboard/documents/'
    | '/dashboard/files/'
    | '/dashboard/mail/'
    | '/dashboard/settings/'
    | '/dashboard/sheets/'
    | '/dashboard/templates/'
    | '/dashboard/voice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/contacts'
    | '/dashboard/documents'
    | '/dashboard/files'
    | '/dashboard/mail'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/dashboard/templates'
    | '/dashboard/voice'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/contacts/'
    | '/dashboard/documents/'
    | '/dashboard/files/'
    | '/dashboard/mail/'
    | '/dashboard/settings/'
    | '/dashboard/sheets/'
    | '/dashboard/templates/'
    | '/dashboard/voice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicBrevoWebhookRoute: typeof ApiPublicBrevoWebhookRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/voice/': {
      id: '/dashboard/voice/'
      path: '/voice'
      fullPath: '/dashboard/voice/'
      preLoaderRoute: typeof DashboardVoiceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sheets/': {
      id: '/dashboard/sheets/'
      path: '/sheets'
      fullPath: '/dashboard/sheets/'
      preLoaderRoute: typeof DashboardSheetsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mail/': {
      id: '/dashboard/mail/'
      path: '/mail'
      fullPath: '/dashboard/mail/'
      preLoaderRoute: typeof DashboardMailIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files/': {
      id: '/dashboard/files/'
      path: '/files'
      fullPath: '/dashboard/files/'
      preLoaderRoute: typeof DashboardFilesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents/': {
      id: '/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof DashboardDocumentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sheets/$documentId': {
      id: '/dashboard/sheets/$documentId'
      path: '/sheets/$documentId'
      fullPath: '/dashboard/sheets/$documentId'
      preLoaderRoute: typeof DashboardSheetsDocumentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents/$documentId': {
      id: '/dashboard/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/dashboard/documents/$documentId'
      preLoaderRoute: typeof DashboardDocumentsDocumentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/jobs-tick': {
      id: '/api/public/jobs-tick'
      path: '/api/public/jobs-tick'
      fullPath: '/api/public/jobs-tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brevo-webhook': {
      id: '/api/public/brevo-webhook'
      path: '/api/public/brevo-webhook'
      fullPath: '/api/public/brevo-webhook'
      preLoaderRoute: typeof ApiPublicBrevoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocumentsDocumentIdRoute: typeof DashboardDocumentsDocumentIdRoute
  DashboardSheetsDocumentIdRoute: typeof DashboardSheetsDocumentIdRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardDocumentsIndexRoute: typeof DashboardDocumentsIndexRoute
  DashboardFilesIndexRoute: typeof DashboardFilesIndexRoute
  DashboardMailIndexRoute: typeof DashboardMailIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSheetsIndexRoute: typeof DashboardSheetsIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardVoiceIndexRoute: typeof DashboardVoiceIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocumentsDocumentIdRoute: DashboardDocumentsDocumentIdRoute,
  DashboardSheetsDocumentIdRoute: DashboardSheetsDocumentIdRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardDocumentsIndexRoute: DashboardDocumentsIndexRoute,
  DashboardFilesIndexRoute: DashboardFilesIndexRoute,
  DashboardMailIndexRoute: DashboardMailIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSheetsIndexRoute: DashboardSheetsIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardVoiceIndexRoute: DashboardVoiceIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicBrevoWebhookRoute: ApiPublicBrevoWebhookRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
