/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignActiveRouteImport } from './routes/sign/active'
import { Route as SignTokenRouteImport } from './routes/sign/$token'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardWorkspaceIndexRouteImport } from './routes/dashboard/workspace/index'
import { Route as DashboardWorkflowsIndexRouteImport } from './routes/dashboard/workflows/index'
import { Route as DashboardVoiceIndexRouteImport } from './routes/dashboard/voice/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardTeamIndexRouteImport } from './routes/dashboard/team/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardSigningIndexRouteImport } from './routes/dashboard/signing/index'
import { Route as DashboardSheetsIndexRouteImport } from './routes/dashboard/sheets/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSearchIndexRouteImport } from './routes/dashboard/search/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/notifications/index'
import { Route as DashboardMailIndexRouteImport } from './routes/dashboard/mail/index'
import { Route as DashboardFilesIndexRouteImport } from './routes/dashboard/files/index'
import { Route as DashboardDocumentsIndexRouteImport } from './routes/dashboard/documents/index'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts/index'
import { Route as DashboardCalendarIndexRouteImport } from './routes/dashboard/calendar/index'
import { Route as DashboardApprovalsIndexRouteImport } from './routes/dashboard/approvals/index'
import { Route as DashboardActivityIndexRouteImport } from './routes/dashboard/activity/index'
import { Route as DashboardWorkflowsRunIdRouteImport } from './routes/dashboard/workflows/$runId'
import { Route as DashboardSheetsDocumentIdRouteImport } from './routes/dashboard/sheets/$documentId'
import { Route as DashboardDocumentsDocumentIdRouteImport } from './routes/dashboard/documents/$documentId'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs-tick'
import { Route as ApiPublicBrevoWebhookRouteImport } from './routes/api/public/brevo-webhook'
import { Route as DashboardSigningRequestIdIndexRouteImport } from './routes/dashboard/signing/$requestId/index'
import { Route as DashboardSigningRequestIdPrepareRouteImport } from './routes/dashboard/signing/$requestId/prepare'
import { Route as DashboardSigningRequestIdPreSignRouteImport } from './routes/dashboard/signing/$requestId/pre-sign'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SignActiveRoute = SignActiveRouteImport.update({
  id: '/sign/active',
  path: '/sign/active',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardWorkspaceIndexRoute = DashboardWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceIndexRoute = DashboardVoiceIndexRouteImport.update({
  id: '/voice/',
  path: '/voice/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamIndexRoute = DashboardTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSigningIndexRoute = DashboardSigningIndexRouteImport.update({
  id: '/signing/',
  path: '/signing/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSheetsIndexRoute = DashboardSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchIndexRoute = DashboardSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMailIndexRoute = DashboardMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesIndexRoute = DashboardFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsIndexRoute = DashboardDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarIndexRoute = DashboardCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsIndexRoute = DashboardApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityIndexRoute = DashboardActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkflowsRunIdRoute = DashboardWorkflowsRunIdRouteImport.update({
  id: '/workflows/$runId',
  path: '/workflows/$runId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSheetsDocumentIdRoute =
  DashboardSheetsDocumentIdRouteImport.update({
    id: '/sheets/$documentId',
    path: '/sheets/$documentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocumentsDocumentIdRoute =
  DashboardDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs-tick',
  path: '/api/public/jobs-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrevoWebhookRoute = ApiPublicBrevoWebhookRouteImport.update({
  id: '/api/public/brevo-webhook',
  path: '/api/public/brevo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSigningRequestIdIndexRoute =
  DashboardSigningRequestIdIndexRouteImport.update({
    id: '/signing/$requestId/',
    path: '/signing/$requestId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSigningRequestIdPrepareRoute =
  DashboardSigningRequestIdPrepareRouteImport.update({
    id: '/signing/$requestId/prepare',
    path: '/signing/$requestId/prepare',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSigningRequestIdPreSignRoute =
  DashboardSigningRequestIdPreSignRouteImport.update({
    id: '/signing/$requestId/pre-sign',
    path: '/signing/$requestId/pre-sign',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/sign/active': typeof SignActiveRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/workflows/$runId': typeof DashboardWorkflowsRunIdRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/approvals/': typeof DashboardApprovalsIndexRoute
  '/dashboard/calendar/': typeof DashboardCalendarIndexRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/files/': typeof DashboardFilesIndexRoute
  '/dashboard/mail/': typeof DashboardMailIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/search/': typeof DashboardSearchIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets/': typeof DashboardSheetsIndexRoute
  '/dashboard/signing/': typeof DashboardSigningIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice/': typeof DashboardVoiceIndexRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
  '/dashboard/signing/$requestId/pre-sign': typeof DashboardSigningRequestIdPreSignRoute
  '/dashboard/signing/$requestId/prepare': typeof DashboardSigningRequestIdPrepareRoute
  '/dashboard/signing/$requestId/': typeof DashboardSigningRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/sign/active': typeof SignActiveRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/workflows/$runId': typeof DashboardWorkflowsRunIdRoute
  '/dashboard/activity': typeof DashboardActivityIndexRoute
  '/dashboard/approvals': typeof DashboardApprovalsIndexRoute
  '/dashboard/calendar': typeof DashboardCalendarIndexRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/files': typeof DashboardFilesIndexRoute
  '/dashboard/mail': typeof DashboardMailIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/search': typeof DashboardSearchIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets': typeof DashboardSheetsIndexRoute
  '/dashboard/signing': typeof DashboardSigningIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice': typeof DashboardVoiceIndexRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
  '/dashboard/workspace': typeof DashboardWorkspaceIndexRoute
  '/dashboard/signing/$requestId/pre-sign': typeof DashboardSigningRequestIdPreSignRoute
  '/dashboard/signing/$requestId/prepare': typeof DashboardSigningRequestIdPrepareRoute
  '/dashboard/signing/$requestId': typeof DashboardSigningRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/sign/active': typeof SignActiveRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/brevo-webhook': typeof ApiPublicBrevoWebhookRoute
  '/api/public/jobs-tick': typeof ApiPublicJobsTickRoute
  '/dashboard/documents/$documentId': typeof DashboardDocumentsDocumentIdRoute
  '/dashboard/sheets/$documentId': typeof DashboardSheetsDocumentIdRoute
  '/dashboard/workflows/$runId': typeof DashboardWorkflowsRunIdRoute
  '/dashboard/activity/': typeof DashboardActivityIndexRoute
  '/dashboard/approvals/': typeof DashboardApprovalsIndexRoute
  '/dashboard/calendar/': typeof DashboardCalendarIndexRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/files/': typeof DashboardFilesIndexRoute
  '/dashboard/mail/': typeof DashboardMailIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/search/': typeof DashboardSearchIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sheets/': typeof DashboardSheetsIndexRoute
  '/dashboard/signing/': typeof DashboardSigningIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/voice/': typeof DashboardVoiceIndexRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
  '/dashboard/signing/$requestId/pre-sign': typeof DashboardSigningRequestIdPreSignRoute
  '/dashboard/signing/$requestId/prepare': typeof DashboardSigningRequestIdPrepareRoute
  '/dashboard/signing/$requestId/': typeof DashboardSigningRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/sign/$token'
    | '/sign/active'
    | '/dashboard/'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/workflows/$runId'
    | '/dashboard/activity/'
    | '/dashboard/approvals/'
    | '/dashboard/calendar/'
    | '/dashboard/contacts/'
    | '/dashboard/documents/'
    | '/dashboard/files/'
    | '/dashboard/mail/'
    | '/dashboard/notifications/'
    | '/dashboard/search/'
    | '/dashboard/settings/'
    | '/dashboard/sheets/'
    | '/dashboard/signing/'
    | '/dashboard/tasks/'
    | '/dashboard/team/'
    | '/dashboard/templates/'
    | '/dashboard/voice/'
    | '/dashboard/workflows/'
    | '/dashboard/workspace/'
    | '/dashboard/signing/$requestId/pre-sign'
    | '/dashboard/signing/$requestId/prepare'
    | '/dashboard/signing/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/sign/$token'
    | '/sign/active'
    | '/dashboard'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/workflows/$runId'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/calendar'
    | '/dashboard/contacts'
    | '/dashboard/documents'
    | '/dashboard/files'
    | '/dashboard/mail'
    | '/dashboard/notifications'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/dashboard/signing'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/voice'
    | '/dashboard/workflows'
    | '/dashboard/workspace'
    | '/dashboard/signing/$requestId/pre-sign'
    | '/dashboard/signing/$requestId/prepare'
    | '/dashboard/signing/$requestId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/invite/$token'
    | '/sign/$token'
    | '/sign/active'
    | '/dashboard/'
    | '/api/public/brevo-webhook'
    | '/api/public/jobs-tick'
    | '/dashboard/documents/$documentId'
    | '/dashboard/sheets/$documentId'
    | '/dashboard/workflows/$runId'
    | '/dashboard/activity/'
    | '/dashboard/approvals/'
    | '/dashboard/calendar/'
    | '/dashboard/contacts/'
    | '/dashboard/documents/'
    | '/dashboard/files/'
    | '/dashboard/mail/'
    | '/dashboard/notifications/'
    | '/dashboard/search/'
    | '/dashboard/settings/'
    | '/dashboard/sheets/'
    | '/dashboard/signing/'
    | '/dashboard/tasks/'
    | '/dashboard/team/'
    | '/dashboard/templates/'
    | '/dashboard/voice/'
    | '/dashboard/workflows/'
    | '/dashboard/workspace/'
    | '/dashboard/signing/$requestId/pre-sign'
    | '/dashboard/signing/$requestId/prepare'
    | '/dashboard/signing/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  SignActiveRoute: typeof SignActiveRoute
  ApiPublicBrevoWebhookRoute: typeof ApiPublicBrevoWebhookRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sign/active': {
      id: '/sign/active'
      path: '/sign/active'
      fullPath: '/sign/active'
      preLoaderRoute: typeof SignActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/workspace/': {
      id: '/dashboard/workspace/'
      path: '/workspace'
      fullPath: '/dashboard/workspace/'
      preLoaderRoute: typeof DashboardWorkspaceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows/'
      preLoaderRoute: typeof DashboardWorkflowsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice/': {
      id: '/dashboard/voice/'
      path: '/voice'
      fullPath: '/dashboard/voice/'
      preLoaderRoute: typeof DashboardVoiceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team/': {
      id: '/dashboard/team/'
      path: '/team'
      fullPath: '/dashboard/team/'
      preLoaderRoute: typeof DashboardTeamIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signing/': {
      id: '/dashboard/signing/'
      path: '/signing'
      fullPath: '/dashboard/signing/'
      preLoaderRoute: typeof DashboardSigningIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sheets/': {
      id: '/dashboard/sheets/'
      path: '/sheets'
      fullPath: '/dashboard/sheets/'
      preLoaderRoute: typeof DashboardSheetsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search/': {
      id: '/dashboard/search/'
      path: '/search'
      fullPath: '/dashboard/search/'
      preLoaderRoute: typeof DashboardSearchIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mail/': {
      id: '/dashboard/mail/'
      path: '/mail'
      fullPath: '/dashboard/mail/'
      preLoaderRoute: typeof DashboardMailIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/files/': {
      id: '/dashboard/files/'
      path: '/files'
      fullPath: '/dashboard/files/'
      preLoaderRoute: typeof DashboardFilesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents/': {
      id: '/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents/'
      preLoaderRoute: typeof DashboardDocumentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar/': {
      id: '/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof DashboardCalendarIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals/': {
      id: '/dashboard/approvals/'
      path: '/approvals'
      fullPath: '/dashboard/approvals/'
      preLoaderRoute: typeof DashboardApprovalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity/': {
      id: '/dashboard/activity/'
      path: '/activity'
      fullPath: '/dashboard/activity/'
      preLoaderRoute: typeof DashboardActivityIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/$runId': {
      id: '/dashboard/workflows/$runId'
      path: '/workflows/$runId'
      fullPath: '/dashboard/workflows/$runId'
      preLoaderRoute: typeof DashboardWorkflowsRunIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sheets/$documentId': {
      id: '/dashboard/sheets/$documentId'
      path: '/sheets/$documentId'
      fullPath: '/dashboard/sheets/$documentId'
      preLoaderRoute: typeof DashboardSheetsDocumentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents/$documentId': {
      id: '/dashboard/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/dashboard/documents/$documentId'
      preLoaderRoute: typeof DashboardDocumentsDocumentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/jobs-tick': {
      id: '/api/public/jobs-tick'
      path: '/api/public/jobs-tick'
      fullPath: '/api/public/jobs-tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brevo-webhook': {
      id: '/api/public/brevo-webhook'
      path: '/api/public/brevo-webhook'
      fullPath: '/api/public/brevo-webhook'
      preLoaderRoute: typeof ApiPublicBrevoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/signing/$requestId/': {
      id: '/dashboard/signing/$requestId/'
      path: '/signing/$requestId'
      fullPath: '/dashboard/signing/$requestId/'
      preLoaderRoute: typeof DashboardSigningRequestIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signing/$requestId/prepare': {
      id: '/dashboard/signing/$requestId/prepare'
      path: '/signing/$requestId/prepare'
      fullPath: '/dashboard/signing/$requestId/prepare'
      preLoaderRoute: typeof DashboardSigningRequestIdPrepareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signing/$requestId/pre-sign': {
      id: '/dashboard/signing/$requestId/pre-sign'
      path: '/signing/$requestId/pre-sign'
      fullPath: '/dashboard/signing/$requestId/pre-sign'
      preLoaderRoute: typeof DashboardSigningRequestIdPreSignRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocumentsDocumentIdRoute: typeof DashboardDocumentsDocumentIdRoute
  DashboardSheetsDocumentIdRoute: typeof DashboardSheetsDocumentIdRoute
  DashboardWorkflowsRunIdRoute: typeof DashboardWorkflowsRunIdRoute
  DashboardActivityIndexRoute: typeof DashboardActivityIndexRoute
  DashboardApprovalsIndexRoute: typeof DashboardApprovalsIndexRoute
  DashboardCalendarIndexRoute: typeof DashboardCalendarIndexRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardDocumentsIndexRoute: typeof DashboardDocumentsIndexRoute
  DashboardFilesIndexRoute: typeof DashboardFilesIndexRoute
  DashboardMailIndexRoute: typeof DashboardMailIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardSearchIndexRoute: typeof DashboardSearchIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSheetsIndexRoute: typeof DashboardSheetsIndexRoute
  DashboardSigningIndexRoute: typeof DashboardSigningIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardTeamIndexRoute: typeof DashboardTeamIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardVoiceIndexRoute: typeof DashboardVoiceIndexRoute
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
  DashboardWorkspaceIndexRoute: typeof DashboardWorkspaceIndexRoute
  DashboardSigningRequestIdPreSignRoute: typeof DashboardSigningRequestIdPreSignRoute
  DashboardSigningRequestIdPrepareRoute: typeof DashboardSigningRequestIdPrepareRoute
  DashboardSigningRequestIdIndexRoute: typeof DashboardSigningRequestIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocumentsDocumentIdRoute: DashboardDocumentsDocumentIdRoute,
  DashboardSheetsDocumentIdRoute: DashboardSheetsDocumentIdRoute,
  DashboardWorkflowsRunIdRoute: DashboardWorkflowsRunIdRoute,
  DashboardActivityIndexRoute: DashboardActivityIndexRoute,
  DashboardApprovalsIndexRoute: DashboardApprovalsIndexRoute,
  DashboardCalendarIndexRoute: DashboardCalendarIndexRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardDocumentsIndexRoute: DashboardDocumentsIndexRoute,
  DashboardFilesIndexRoute: DashboardFilesIndexRoute,
  DashboardMailIndexRoute: DashboardMailIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardSearchIndexRoute: DashboardSearchIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSheetsIndexRoute: DashboardSheetsIndexRoute,
  DashboardSigningIndexRoute: DashboardSigningIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardTeamIndexRoute: DashboardTeamIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardVoiceIndexRoute: DashboardVoiceIndexRoute,
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
  DashboardWorkspaceIndexRoute: DashboardWorkspaceIndexRoute,
  DashboardSigningRequestIdPreSignRoute: DashboardSigningRequestIdPreSignRoute,
  DashboardSigningRequestIdPrepareRoute: DashboardSigningRequestIdPrepareRoute,
  DashboardSigningRequestIdIndexRoute: DashboardSigningRequestIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  SignTokenRoute: SignTokenRoute,
  SignActiveRoute: SignActiveRoute,
  ApiPublicBrevoWebhookRoute: ApiPublicBrevoWebhookRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
