// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydgsmnzcwkrlghlhtpgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZ3Ntbnpjd2tybGdobGh0cGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5Mjc3OTcsImV4cCI6MjA5NzUwMzc5N30.mqj9FJ3L92r62lsfYL6jHEgWRdEc-x0MqDNVrhTmnvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});